"""add role to reg

Revision ID: 60f9e5fcb1d0
Revises: 51e46753255b
Create Date: 2024-11-13 13:00:20.074460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f9e5fcb1d0'
down_revision = '51e46753255b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reg', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
