"""change to reg

Revision ID: 7619a694629c
Revises: 2e00821d7f02
Create Date: 2024-11-12 17:46:03.465360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7619a694629c'
down_revision = '2e00821d7f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_constraint('payment_methods_customer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'reg', ['customer_id'], ['customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_methods_customer_id_fkey', 'customers', ['customer_id'], ['customer_id'])

    # ### end Alembic commands ###
