"""change to regs to cust

Revision ID: e0a7ad97668a
Revises: fc955417832b
Create Date: 2024-11-12 23:27:16.981832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a7ad97668a'
down_revision = 'fc955417832b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_customer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'reg', ['customer_id'], ['customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_customer_id_fkey', 'customers', ['customer_id'], ['customer_id'])

    # ### end Alembic commands ###
