"""change to regs

Revision ID: fc955417832b
Revises: 7619a694629c
Create Date: 2024-11-12 17:50:25.154085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc955417832b'
down_revision = '7619a694629c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint('feedback_customer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'reg', ['customer_id'], ['customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('feedback_customer_id_fkey', 'customers', ['customer_id'], ['customer_id'])

    # ### end Alembic commands ###
